embed_assets: on

javascripts:
  workspace:
    - public/javascripts/lib/jquery.js
    - public/javascripts/jquery.rails.js
    - public/javascripts/lib/showdown.js
    - public/javascripts/lib/mustache.js
    - public/javascripts/lib/underscore-min.js
    - public/javascripts/lib/backbone-min.js
    - public/javascripts/app.js
    - public/javascripts/controllers/*.js
    - public/javascripts/models/*.js
    - public/javascripts/collections/*.js   
    - public/javascripts/views/**/*.js
    
stylesheets:
  common:
    - public/stylesheets/bw.css
  workspace:
    - public/stylesheets/bw.css
  empty:
    - public/stylesheets/bw.css
