# Here you can specify default options for TinyMCE across all controllers
#
 theme: advanced
 #theme_advanced_resizing: true
 theme_advanced_toolbar_location: top
 #plugins:
#  - table
#  - fullscreen
